### ISSUE TITLE
Make placeholder text color identical in `TextInput` and `TextArea` by default

### ISSUE THREAD

**Issue by appliquant** [atomlabdev/elements#2]
Hello, 

Placeholder text color of `TextInput` and `TextArea` should be the same. You could add this to each components : 

```ts
placeholderTextColor={tailwind.color("text-gray-400")}
```

Components : 

- `TextInput` : https://www.atomlab.dev/elements/components/text-area
- `TextArea` : https://www.atomlab.dev/elements/components/text-area

Btw, thank you for making this!

**Comment by appliquant** [comment]
Nervermind, you can actually set `placeholderTextColor` directly in component like so :

```ts
<TextInput className={`mt-10`} placeholderTextColor={...}  />
```

**Comment by atomlabdev** [comment]
You can but I think you're correct that we should set be setting a consistent default value, I'll look at this in the next release
