### ISSUE TITLE
`ButtonGroup` items should have `key` prop

### ISSUE THREAD

**Issue by appliquant** [atomlabdev/elements#3]
Hello,

In [`button-group.tsx` component](https://www.atomlab.dev/elements/components/button-group), a `key` prop should be specified, otherwise, you get a warning : `each child in a list should have a unique "key" prop`.

As a solution, the interface `ButtonGroupItem` could take a key, which would be passed to the loop inside `ButtonGroup` as a key.

Thanks :)

**Comment by atomlabdev** [comment]
Thanks @appliquant , not sure how I missed this! Fixed in v0.7.1
